"Language" = "en"

[Translations]
"Chat.Format.Other"             = "{Channel:choose(0|1|2|3|4|5):{:L:Chat.Format.Other.Whisper}|{:L:Chat.Format.Other.Local}|{:L:Chat.Format.Other.System}|{:L:Chat.Format.Other.Global}|{:L:Chat.Format.Other.Help}|{:L:Chat.Format.Other.Trade}|{:L:Chat.Format.Other.Default}}"
"Chat.Format.Other.Whisper"     = "{Sender} whispers to you, \"{Value}\""
"Chat.Format.Other.Local"       = "{Sender} says, \"{Value}\""
"Chat.Format.Other.System"      = "[System] {Value}"
"Chat.Format.Other.Global"      = "[Global] {Sender} says, \"{Value}\""
"Chat.Format.Other.Help"        = "[Help] {Sender} says, \"{Value}\""
"Chat.Format.Other.Trade"       = "[Trade] {Sender} says, \"{Value}\""
"Chat.Format.Other.Default"     = "{Sender} says, \"{Value}\""

"Chat.Format.Self"              = "{Channel:choose(0|1|2|3|4|5):{:L:Chat.Format.Self.Whisper}|{:L:Chat.Format.Self.Local}|{:L:Chat.Format.Self.System}|{:L:Chat.Format.Self.Global}|{:L:Chat.Format.Self.Help}|{:L:Chat.Format.Self.Trade}|{:L:Chat.Format.Self.Default}}"
"Chat.Format.Self.Whisper"      = "You whisper to {Target}, \"{Value}\""
"Chat.Format.Self.Local"        = "You say, \"{Value}\""
"Chat.Format.Self.System"       = "[System] {Value}"
"Chat.Format.Self.Global"       = "[Global] You say, \"{Value}\""
"Chat.Format.Self.Help"         = "[Help] You say, \"{Value}\""
"Chat.Format.Self.Trade"        = "[Trade] You say, \"{Value}\""
"Chat.Format.Self.Default"      = "You say, \"{Value}\""
